# Sử dụng node để build ứng dụng
FROM node:20 AS build

# Tạo thư mục làm việc
WORKDIR /app

# Copy package.json và package-lock.json vào container
COPY package*.json ./

# Cài đặt dependencies
RUN npm install

# Copy toàn bộ source code vào container
COPY . .

# Build ứng dụng cho production
RUN npm run build

# Sử dụng nginx để serv ứng dụng React đã build
FROM nginx:stable-alpine

# Copy build từ giai đoạn build vào nginx public forder
COPY --from=build /app/dist /usr/share/nginx/html

# Copy file cấu hình nginx custom
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy file cấu hình nginx (nếu cần)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]