const daysAgo = (n, h=12, m=0) => {
    const d = new Date();
    d.setHours(h, m, 0, 0);
    d.setDate(d.getDate() - n);
    return d.toISOString();
};

export const AUDIT_EVENTS = [
    { id:"evt_001", timestamp: daysAgo(1,17,30), actor:"Sarah Johnson", action:"User Created",
        resource:"john.doe@englishcenter.edu", details:"New teacher account created", ip:"192.168.1.100" },
    { id:"evt_002", timestamp: daysAgo(1,16,15), actor:"Mike Chen", action:"License Assigned",
        resource:"Microsoft Office 365", details:"License assigned to new user", ip:"192.168.1.105" },
    { id:"evt_003", timestamp: daysAgo(1,15,45), actor:"System", action:"Software Deployed",
        resource:"Zoom Client v5.16.2", details:"Automatic deployment to Pilot ring completed", ip:"N/A" },
    { id:"evt_004", timestamp: daysAgo(2,10,5), actor:"AdminIT", action:"Password Reset",
        resource:"thao.nguyen@englishcenter.edu", details:"Temporary password generated by AdminIT", ip:"10.0.0.42" },
    { id:"evt_005", timestamp: daysAgo(3,19,22), actor:"Bao Tran", action:"Role Updated",
        resource:"teacher → manager", details:"Granted manager permissions to Bao Tran", ip:"172.16.0.7" },
    { id:"evt_006", timestamp: daysAgo(3,9,10), actor:"System", action:"Policy Applied",
        resource:"MFA Enforcement", details:"Enabled MFA enforcement for all staff accounts", ip:"N/A" },
    { id:"evt_007", timestamp: daysAgo(4,14,40), actor:"Linh Pham", action:"User Disabled",
        resource:"old.student@englishcenter.edu", details:"Account disabled due to inactivity", ip:"192.168.2.33" },
    { id:"evt_008", timestamp: daysAgo(5,8,55), actor:"System", action:"Login Failed",
        resource:"teacher.portal", details:"5 failed attempts detected (rate limited)", ip:"203.113.5.21" },
    { id:"evt_009", timestamp: daysAgo(6,11,28), actor:"Quang Le", action:"Group Changed",
        resource:"Class Owners", details:"Added user to group: ENG101_Autumn", ip:"192.168.1.77" },
];

export const DATE_RANGE_OPTIONS = [
    { label:"Today", value:"today" },
    { label:"Last 7 days", value:"7d" },
    { label:"Last 30 days", value:"30d" },
    { label:"All time", value:"all" },
];

export const ACTION_OPTIONS = [
    { label:"All actions", value:"all" },
    ...Array.from(new Set(AUDIT_EVENTS.map(e => e.action))).map(a => ({ label:a, value:a })),
];

export const ACTOR_OPTIONS = [
    { label:"All actors", value:"all" },
    ...Array.from(new Set(AUDIT_EVENTS.map(e => e.actor))).map(a => ({ label:a, value:a })),
];
export default AUDIT_EVENTS;
