spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${DBMS_URL:jdbc:sqlserver://localhost:1433;databaseName=dev_lms_management;encrypt=true;trustServerCertificate=true}
    username: ${DBMS_USERNAME:sa}
    password: ${DBMS_PASSWORD:123}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        javax.persistence.validation.mode: AUTO
        hibernate.validator.fail_fast: false
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: lsm-service
    server: http://${OPENAPI_SERVER_URL:localhost:8081}:${server.port}
    title: Lms service
    version: 1.0.0

jwt:
  secretKey: dev@123
  expiryMinutes: ${EXPIRY_MINUTES:5}
  expiryDay: ${EXPIRY_DAY:10}
  accessKey: 1ef1ed938c82d16798fa1ec4300d3571988b1b37b9116a7e70c6def68bff3516
  refreshKey: 0021f3009a0d7a65b84fd75c056ec4c6a46ca6b9961e7cecfd7ffa38e3fc9dd4

minio:
  hostname: ${MINIO_ENDPOIND:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucketName: ${MINIO_BUCKET_NAME:lms-bucket}
  region: ${MINIO_REGION:us-east-1}

vnpay:
  tmnCode: ${VNPAY_TMN_CODE:0GK43HDP}
  hashSecret: ${VNPAY_HASH_SECRET:OLBPY32TY1VB9MAG2UGSPHGGI7F4HPEM}
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: ${RETURN_URL:http://localhost:8081/api/v1/payments/vnpay-return}
  ipnUrl: ${IPN_URL:http://localhost:8081/api/v1/payments/vnpay-ipn}

client:
  domain: ${DOMAIN:http://localhost:5173}