server:
  port: 8081

spring:
  application:
    name: lms-service
  profiles:
    active: @spring.profiles.active@
  data:
    redis:
      host: 14.225.198.117
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: '*'
        # include: health,prometheus,metrics

logging:
  level:
    root: INFO
    web: INFO