services:

  lms-service-dev:
    container_name: lms-service-dev
    #image: hoangson93/lms-service:latest

    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      OPENAPI_SERVER_URL: 14.225.198.117
      SPRING_PROFILES_ACTIVE: dev
      DBMS_PASSWORD: 123456Aa@
      DBMS_URL: jdbc:sqlserver://14.225.198.117:1433;databaseName=dev_lms_management;encrypt=true;trustServerCertificate=true
      DBMS_USERNAME: son
      MINIO_ACCESS_KEY: admin
      MINIO_ENDPOINT: http://14.225.198.117:9000
      MINIO_SECRET_KEY: minio123456
      MINIO_BUCKET_NAME: test-upload

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
        - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment: # account: grafana/password
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - '3000:3000'
    links:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana

networks:
  default:
    name: lms-service

volumes:
  grafana:


#docker run -d -p 8081:8081 -e OPENAPI_SERVER_URL=14.225.198.117 -e SPRING_PROFILES_ACTIVE=dev -e DBMS_PASSWORD=123456Aa@ -e DBMS_URL="jdbc:sqlserver://14.225.198.117:1433;databaseName=dev_lms_management;encrypt=true;trustServerCertificate=true" -e DBMS_USERNAME=son -e MINIO_ACCESS_KEY=admin -e MINIO_ENDPOINT=http://14.225.198.117:9000 -e MINIO_SECRET_KEY=minio123456 -e MINIO_BUCKET_NAME=test-upload hoangson93/lms-service:0.0.1-arm64