global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'lms-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lms-service-dev:8081']
        labels:
          application: 'lms-service'